### ISSUE TITLE
Telescope toolbar not compatible with telescope ^3.0

### ISSUE THREAD

**Issue by RSpeekenbrink** [fruitcake/laravel-telescope-toolbar#17]
Telescope ^3.0 released 20 hours ago (https://github.com/laravel/telescope/releases). It removed support for Laravel 5.8. Will the toolbar drop support for 5.8 aswell and move to a new major?

**Comment by barryvdh** [comment]
I think we can support both. https://github.com/fruitcake/laravel-telescope-toolbar/pull/18
