### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by JonPurvis** [fruitcake/laravel-telescope-toolbar#23]
Hello, I recently updated the toolbar version I'm using to 1.2, (on Laravel 6.16.0) - none of the icons appear to be showing in the toolbar:

![image](https://user-images.githubusercontent.com/7534029/75179737-a36c8180-5732-11ea-8c21-344a54e05ab8.png)

I've tried removing / re-requiring through composer, didn't make a difference.

Any help would be appreciated, thanks!

**Comment by barryvdh** [comment]
You have Blade enabled right? Not really sure what's going on here. It worked before?

**Comment by JonPurvis** [comment]
Yeah Blade is enabled, I've checked the network tab in my browser and nothing is being blocked. I'll keep an eye on it, I'm hoping it'll sort itself out 🤞 I just wanted to see if anyone else was experiencing it.

Also running Laravel 6.17.0 now, doesn't seem to make a difference though.

**Comment by larryx64** [comment]
Did you try running `artisan view:clear` to clear all compiled views?

I've had that happened with some other packages and it solved my problem.

**Comment by JonPurvis** [comment]
@larryx64 Yep, I've ran that a bunch of times but still getting no icons!

**Comment by barryvdh** [comment]
Hmm I'm adding the Blade direct here: https://github.com/fruitcake/laravel-telescope-toolbar/blob/7b51222f644e558696ec684a7199572dbb3ff6b4/src/Http/Controllers/ToolbarController.php#L117-L120
Not sure if that's cached or something.

**Comment by JonPurvis** [comment]
Tried this on Chrome Incognito and Chromium last night and get no icons on there either 😢 

I'll continue trying to debug

**Comment by JonPurvis** [comment]
Just jumping back on here to let you know it's sorted!

I've upgraded my app to Laravel 7 and ran `view:cache` and it seems to have done the trick!
