### ISSUE TITLE
Don't load Toolbar on some paths

### ISSUE THREAD

**Issue by mikemand** [fruitcake/laravel-telescope-toolbar#25]
Telescope itself has the ability to ignore some paths (for example, a third-party package that has its own routes). Is this something we can have for the Toolbar too?

Currently, the Toolbar will be injected into any HTML response. However, it isn't too intelligent as to which responses are actually HTML. If a header wasn't supplied, it is assumed that the response is HTML.

**Comment by barryvdh** [comment]
Hmm not sure if we assume html, or Laravel uses that default header. But we could perhaps check for actual html tags.

**Comment by mikemand** [comment]
Hi Barry,

Yeah, I think Laravel does that itself. If I read the source for the toolbar correctly, when it is injected it does check for HTML headers: https://github.com/fruitcake/laravel-telescope-toolbar/blob/7b51222f644e558696ec684a7199572dbb3ff6b4/src/Toolbar.php#L91

**Comment by barryvdh** [comment]
Yeah but I think we also check for Ajax requests and don't ignore there either. Same with laravel-debugbar and I don't hear problems often. What does the route do exactly?

**Comment by mikemand** [comment]
Hi Barry,

It uploads a file and returns the path: https://github.com/cnvs/canvas/blob/b2e5ded3dce6a05c0bad75af653e3667d53d7cae/src/Http/Controllers/MediaController.php#L16-L30

The file uploader that Canvas uses needs the file path returned to it as plain text. I've asked if they would add a response header before the return but they will not. I'm not sure why their route is not being treated as AJAX, but it's also probably a header issue.

**Comment by mikemand** [comment]
It looks like this is now fixed by #42. Thank you @Braunson!
