### ISSUE TITLE
No Toolbar on HTTPS -> requested an insecure XMLHttpRequest endpoint

### ISSUE THREAD

**Issue by LTKort** [fruitcake/laravel-telescope-toolbar#31]
Cant figure it out with the new HTTPS configuration, see error from console below.

It wont load in Chrome (it does load in IE though ;) ).

`VM106:1 Mixed Content: The page at 'https://DOMAIN.TLD/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://DOMAIN.TLD/_tt/render/9037011f-4885-4657-8a25-10b8ea29032c'. This request has been blocked; the content must be served over HTTPS.`

**Comment by Braunson** [comment]
Try forcing the URL scheme in your `RouteServiceProvider.php`, that seemed to resolve the issue for me. Place this in the boot method.

```php
resolve(\Illuminate\Routing\UrlGenerator::class)->forceScheme('https');
```
