### ISSUE TITLE
Release for PHP 8 support

### ISSUE THREAD

**Issue by laurensgroeneveld** [fruitcake/laravel-telescope-toolbar#53]
In #49 PHP 8 support was added, but there was no release since then so with the current version composer will give the following error:
```
    - fruitcake/laravel-telescope-toolbar v1.3.0 requires php ^7.3 -> your php version (8.0.3) does not satisfy that requirement.
```

I temporarily switched to `dev-master` in my composer.json, but I propose to release a new version which includes this support.

**Comment by barryvdh** [comment]
Is tagges

**Comment by laurensgroeneveld** [comment]
Thanks, works like a charm 🙌
