### ISSUE TITLE
Laravel 11 and PHP 8.2 support

### ISSUE THREAD

**Issue by segungreat** [fruitcake/laravel-telescope-toolbar#78]
On a new Laravel 11 installation. Installation of laravel telescope installed version 5. But when I ran 'composer require fruitcake/laravel-telescope-toolbar --dev' it failed with the following messages.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fruitcake/laravel-telescope-toolbar[v1.0.0, ..., v1.2.5] require php ^7.1.3 -> your php version (8.2.16) does not satisfy that requirement.
    - fruitcake/laravel-telescope-toolbar v1.3.0 requires php ^7.3 -> your php version (8.2.16) does not satisfy that requirement.
    - fruitcake/laravel-telescope-toolbar v1.3.1 requires laravel/framework ^8 -> found laravel/framework[v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.0).
    - fruitcake/laravel-telescope-toolbar v1.3.2 requires laravel/framework ^8|^9 -> found laravel/framework[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.0).
    - fruitcake/laravel-telescope-toolbar v1.3.3 requires laravel/framework ^9|^10 -> found laravel/framework[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.2] but it conflicts with your root composer.json require (^11.0).
    - fruitcake/laravel-telescope-toolbar v1.3.4 requires laravel/telescope ^4 -> found laravel/telescope[v4.0.0, ..., v4.17.6] but it conflicts with your root composer.json require (^5.0).
    - Root composer.json requires fruitcake/laravel-telescope-toolbar * -> satisfiable by fruitcake/laravel-telescope-toolbar[v1.0.0, ..., v1.3.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require fruitcake/laravel-telescope-toolbar:*" to figure out if any version is installable, or "composer require fruitcake/laravel-telescope-toolbar:^2.1" if you know which you need.

How can I solve this? Thank you.

**Comment by barryvdh** [comment]
Latest release supports telescope 5 now
